//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfflineMapBook.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1900-01-02")]
        public global::System.DateTime MmpkDownloadDate {
            get {
                return ((global::System.DateTime)(this["MmpkDownloadDate"]));
            }
            set {
                this["MmpkDownloadDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OfflineMapbookTest.mmpk")]
        public string MmpkFileName {
            get {
                return ((string)(this["MmpkFileName"]));
            }
            set {
                this["MmpkFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://runtime.maps.arcgis.com/sharing/rest")]
        public string PortalUri {
            get {
                return ((string)(this["PortalUri"]));
            }
            set {
                this["PortalUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5ca1aba9eb05490f84b66bf9bbe4cc10")]
        public string PortalItemID {
            get {
                return ((string)(this["PortalItemID"]));
            }
            set {
                this["PortalItemID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloadPath {
            get {
                return ((string)(this["DownloadPath"]));
            }
            set {
                this["DownloadPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int MapPinHeight {
            get {
                return ((int)(this["MapPinHeight"]));
            }
            set {
                this["MapPinHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OAuth")]
        public string AuthenticationType {
            get {
                return ((string)(this["AuthenticationType"]));
            }
            set {
                this["AuthenticationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fibBFbcGmC5Tyk7r")]
        public string OAuthClientID {
            get {
                return ((string)(this["OAuthClientID"]));
            }
            set {
                this["OAuthClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8dda995e9c094c199418ee73ff0338aa")]
        public string OAuthClientSecret {
            get {
                return ((string)(this["OAuthClientSecret"]));
            }
            set {
                this["OAuthClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://developers.arcgis.com")]
        public string OAuthRedirectUri {
            get {
                return ((string)(this["OAuthRedirectUri"]));
            }
            set {
                this["OAuthRedirectUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OAuthRefreshToken {
            get {
                return ((string)(this["OAuthRefreshToken"]));
            }
            set {
                this["OAuthRefreshToken"] = value;
            }
        }
    }
}
